name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build PWA
      run: npm run build
      
    - name: Copy to Capacitor
      run: |
        # Use local CLI to avoid npx issues
        ./node_modules/.bin/cap copy android || npx cap copy android
      
    - name: Sync Capacitor
      run: |
        # Use local CLI to avoid npx issues
        ./node_modules/.bin/cap sync android || npx cap sync android
      
    - name: Build Debug APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: talethreads-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build Release APK (if on main/master)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Upload Release APK
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: talethreads-release-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
